_extends: repo-settings:.github/iac-onepipeline-settings.yaml

repository:
  name: "terraform-ibm-cloudant"
  description: "Deploys and configures an IBM Cloud Cloudant instance"
  topics: terraform-module, graduated, core-team, supported
