_extends: repo-settings:.github/iac-onepipeline-settings.yaml

repository:
  name: "cloudant-module"
  description: "Deploys and configures an IBM Cloud Cloudant instance"
  topics: terraform-module, graduated, supported, core-team
