_extends: repo-settings:.github/common-settings-v2.yml

repository:
  name: "terraform-ibm-cloudant"
  description: "Deploys and configures an IBM Cloudant instance"
  topics: terraform-module, graduated, core-team, supported, cloudant, deployable-architecture
