---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-cloudant
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 3a7a93d2-2755-4af3-bc8c-eba1e0bc9dda
    variations:
      - name: dedicated
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
